Further Code Clean Up
Kopernicus/Stellarator pull request #12
Opened 2017-08-07 22:05 UTC by MartinX3

Added ToDo's

Fixed moons-String.

Optimized Code further (C#7 conventions)                              

Changed some code to LINQ

2017-08-07 23:55 UTC, StollD requested changes

2017-08-07 23:55 UTC, StollD commented on Source/Database/PQSPreset.cs
> +    using ConfigNodeParser;
Please leave the usings outside of the namespace declaration.

2017-08-07 23:55 UTC, StollD commented on Source/Database/PQSPreset.cs
> +    ///     Prefab for a PQS
I am not sure if I like these leading whitespaces.

2017-08-07 23:55 UTC, StollD commented on Source/Generator.cs
> +        private static int Seed { get; set; }
Please use CLR type names instead of type aliases

2017-08-07 23:55 UTC, StollD commented on Source/Generator.cs
> +            var system = new SolarSystem(false, true, s => { });
Please don't use var.

2017-08-07 23:55 UTC, StollD commented on Source/Generator.cs
> +                    template.AddValue("removeAllPQSmods", "True");
You know that you changed a value that is later read by Kopernicus? Kopernicus is case sensitive

2017-08-07 23:55 UTC, StollD commented on Source/Generator.cs
> +                GeneratePqs(ref node, name, folder, planet, out average);
Please keep it PQS

2017-08-07 23:55 UTC, StollD commented on Source/Generator.cs
> +            var mods = new ConfigNode("mods");
Same as above, you changed a value that is later read by Kopernicus

2017-08-07 23:55 UTC, StollD commented on Source/Generator.cs
> +                                            {
This indent looks weird

2017-08-07 23:55 UTC, StollD commented on Source/Generator.cs
> +                    ) // TODO: Implement something to make strength dynamic
No newline maybe?

2017-08-17 22:01 UTC, MartinX3 commented on Source/Database/PQSPreset.cs
> +    ///     Prefab for a PQS
Should I revert this?
I thought with them, the text between the next nodes is easier to read. :)

2017-08-17 22:25 UTC, MartinX3 commented on Source/Generator.cs
> +                    ) // TODO: Implement something to make strength dynamic
The newline intends a better reading
Should I revert it?

```
diffuse.Bitmap
                               .Save(Directory.GetCurrentDirectory() + "/systems/" + folder + "/PluginData/" + name + "_Texture.png",
                                     ImageFormat.Png);
```

2017-08-17 22:26 UTC, MartinX3 commented on Source/Generator.cs
> +                                            {
ReSharper told it to me, for a better readability
Should i revert it?

2017-08-17 22:35 UTC, MartinX3 commented
I made several commits, to integrate your advises
I look how I can merge them with this pull request.

2017-08-18 10:35 UTC, StollD commented on Source/Generator.cs
> +                    ) // TODO: Implement something to make strength dynamic
In the code I marked, there is a new line for a `)`, I don't think that is neccessary. The comment can stay on the new line though.

2017-08-18 10:37 UTC, StollD commented on Source/Program.cs
> +            string seed = Prompt("Please enter the seed you want to use: ", "--seed");
Please use CLR type names here too

2017-08-19 20:27 UTC, MartinX3 commented
Hey @StollD , is that okay now? :)

2017-08-20 17:23 UTC, MartinX3 commented on Source/Generator.cs
> +                    ) // TODO: Implement something to make strength dynamic
Ahh, It is changed. :)

2017-08-20 17:24 UTC, MartinX3 commented
I also added an Info about the code conventions, you want in this project. :)

2017-08-20 19:47 UTC, StollD commented
Looks ok to me. Merging.

Thanks for your contribution!

2017-08-20 19:48 UTC, StollD approved these changes

2017-08-20 19:49 UTC, MartinX3 commented
Perfect :)
And I'm glad, that you are happy about my contribution :D

2017-08-20 19:49 UTC, merged